version: 0.2

env:
  variables:
    APP_NAME: "fresh"
    S3_BUCKET: "siva14"
    DEPLOYMENT_GROUP: "my-deployment-group"
    REGION: "us-west-2"

phases:
  pre_build:
    commands:
      - echo "Installing Java and maven"
      - sudo apt-get update || echo "apt-get update failed, check the logs."
      - sudo apt-get install -y openjdk-11-jdk
      - sudo apt-get install -y maven awscli
      - java -version


  build:
    commands:
      - echo "Building Spring Boot application with Gradle"
      - mvn clean install

  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "moving jarfile to output"
      - ls
      - BUILD_VERSION=$(TZ=IST date +"%Y-%m-%d-%H-%M-%S")
      - mkdir fresh
      - cp target/*.jar ./fresh/
      - cp appspec.yml startup.sh ./fresh
      - zip -r "fresh_${BUILD_VERSION}.zip" ./fresh
      - aws s3 cp "fresh_${BUILD_VERSION}.zip" s3://siva14
     

cache:
  paths:
    - ~/.m2/repository
